# Generated by Django 5.0 on 2024-03-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_alter_creditnotereference_credit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotereference',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='billapp.creditnote'),
        ),
    ]
